backend:
  image: abhayraj01/founderbrain-backend:latest
  replicas: 1
  port: 8080

frontend:
  image: abhayraj01/founderbrain-frontend:latest
  replicas: 1
  port: 80

mlservice:
  image: abhayraj01/founderbrain-ml:latest
  replicas: 1
  port: 8000
